version: "3"


services:
  server:
    environment:
      - APP_HOST
      - APP_PORT
    build: .
    ports:
      - "8000:${APP_PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    command: postgres -c 'shared_buffers=256MB' -c 'work_mem=8MB'
    ports:
      - "5432:${POSTGRES_PORT}"